Changes to try to get around the errors with views in the last commit (which should have had message below)
Update spack.yaml with @cmacmackin suggestions.

Following the setup of
```
$ cd hermes-3
$ . activate_h3env
$ spack concretize -f -U
$ spack install --only dependencies -j 1
```
I get the following termination of output
```
==> Installing py-xhermes-0.1.0-qkcaoxdykx4w62imunazl7o6xldjsi2q [141/141]
==> No binary for py-xhermes-0.1.0-qkcaoxdykx4w62imunazl7o6xldjsi2q found: installing from source
==> Fetching https://files.pythonhosted.org/packages/source/x/xhermes/xhermes-0.1.0.tar.gz
==> No patches needed for py-xhermes
==> py-xhermes: Executing phase: 'install'
==> py-xhermes: Successfully installed py-xhermes-0.1.0-qkcaoxdykx4w62imunazl7o6xldjsi2q
  Stage: 0.66s.  Install: 0.60s.  Post-install: 0.05s.  Total: 1.52s
[+] /gcc-11.4.0/py-xhermes-0.1.0-qkcaoxdykx4w62imunazl7o6xldjsi2q
==> Updating view at /views/gcc
==> Error: The environment view in /views/gcc could not be created, because the following two specs project to the same prefix:
    py-setuptools@=69.2.0%gcc@=11.4.0 build_system=generic arch=linux-ubuntu22.04-skylake, and
    py-setuptools@=63.4.3%gcc@=11.4.0 build_system=generic arch=linux-ubuntu22.04-skylake.
    To resolve this issue:
        a. use `concretization:unify:true` to ensure there is only one package per spec in the environment, or
        b. disable views with `view:false`, or
        c. create custom view projections.
```

On this commit I use the following installation steps
$ spacktivate -p -d .
$ spack concretize -f -U
$ spack install --only dependencies -j 1
$ spack install --only-concrete -j1 reactions

I can then test reactions via the unit tests.

To test hermes-3, I make a manual install via
$ spack load petsc@3.22.1
$ spack load mpich@4.2.3
$ spack load netcdf-c@4.9.2
$ spack load netcdf-cxx4@4.3.1
$ spack load cmake@3.30.5
$ spack load sundials@7.1.1
$ cmake . -B devbuilds/build -DBOUT_USE_PETSC=ON
$ cd devbuilds/build/
$  cmake --build .

Note that multiple cmake versions are available in this repo, one must be chosen.
Unfortunately, the hermes-3 build fails with error

```
[ 83%] Linking CXX executable hermes-3
/usr/bin/ld: CMakeFiles/hermes-3.dir/hermes-3.cxx.o: in function `Field3D Options::withDefault<Field3D>(Field3D)':
/hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:586: undefined reference to `libintl_dgettext'
/usr/bin/ld: CMakeFiles/hermes-3.dir/hermes-3.cxx.o: in function `void Options::_set<bool>(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
/hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:896: undefined reference to `libintl_dgettext'
/usr/bin/ld: /hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:899: undefined reference to `libintl_dgettext'
/usr/bin/ld: /hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:904: undefined reference to `libintl_dgettext'
/usr/bin/ld: CMakeFiles/hermes-3.dir/hermes-3.cxx.o: in function `bool Options::withDefault<bool>(bool)':
/hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:586: undefined reference to `libintl_dgettext'
/usr/bin/ld: CMakeFiles/hermes-3.dir/hermes-3.cxx.o:/hermes-3-reactions/external/BOUT-dev/include/bout/options.hxx:896: more undefined references to `libintl_dgettext' follow
/usr/bin/ld: external/BOUT-dev/lib/libbout++.so.5.1.0: undefined reference to `libintl_bindtextdomain'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/hermes-3.dir/build.make:118: hermes-3] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:983: CMakeFiles/hermes-3.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```